// app/utils/language.tsx
import { useDirection } from '../app/DirectionContext';

const englishToArabic: Record<string, string> = {
   "welcome Back!": "مرحبا بعودتك!",
   "Login to your account": "تسجيل الدخول إلى حسابك",
   "User Email": "البريد الإلكتروني للمستخدم",
   "Password": "كلمة المرور",
   "Select Location": "حدد الموقع",
   "Location 1": "الموقع 1",
   "Location 2": "الموقع 2",
   "Remember me": "تذكرني",
   "Forgot password?": "هل نسيت كلمة المرور؟",
   "LOGIN": "تسجيل الدخول",
   "Redefining Employee Management":"إعادة تعريف إدارة الموظفين",
   "Foster a connected workforce with our all-in-one ERP solution.":"عزز قوة عاملة متصلة من خلال حل تخطيط موارد المؤسسات (ERP) الشامل لدينا.",
   "Complete Employee Management Platform":"منصة كاملة لإدارة الموظفين",
   "From recruitment to retirement, manage every employee journey seamlessly and efficiently.":"من التوظيف إلى التقاعد، قم بإدارة رحلة كل موظف بسلاسة وكفاءة.",
   "The Future of Workforce Management":"مستقبل إدارة القوى العاملة",
   "Boost Engagement and Compliance with Intuitive ERP Solutions.":"تعزيز المشاركة والامتثال من خلال حلول تخطيط موارد المؤسسات (ERP) البديهية.",
   "January": "يناير",
   "February": "فبراير",
   "March": "مارس",
   "April": "أبريل",
   "May": "مايو",
   "June": "يونيو",
   "July": "يوليو",
   "August": "أغسطس",
   "September": "سبتمبر",
   "October": "أكتوبر",
   "November": "نوفمبر",
   "December": "ديسمبر",
   'ABSENT':'غائب',
   'LEAVE':'يترك',
   'LOAN':'يُقرض',
   'Late In, Early Out':"في وقت متأخر، في وقت مبكر للخروج",
   'Attendance':'حضور',
   'Remarks':"ملاحظات",
   'Type':'يكتب',
   'Location':'موقع',
   'Check In':'الدفع',
   'Check Out':'تحقق في',
   'Office':'مكتب',
   'Client':'عميل',
   'Home':'بيت',
   'Date':'تاريخ',
   'In':'في',
   'Out':'خارج',
   'Shift':'يحول',
   'Training':'تمرين',
   'Attend Date':"تاريخ الحضور",
  'Request Training':"طلب التدريب",
  'Select Training':"اختر التدريب",
  'Choose a training':"اختر التدريب",
  "Pref. Date":"التاريخ المفضل",
  "Reason":"سبب",
  'Save':'يحفظ',
  'Cancel':'يلغي',
  'Holidays':'العطل',
  'Description':'وصف',
  'Documents':'وثائق',
  'Actions':"الإجراءات",
  'Image':'صورة',
  'Expiry':"انتهاء الصلاحية",
  'Number':'رقم',
  'Staff Ledger':"دفتر حسابات الموظفين",
  'Account':'حساب',
  'Ref#':"المرجع #",
  'Amount':'كمية',
  "Announcements":"الإعلانات",
  "Latest announcements will appear here.":"أحدث الإعلانات ستظهر هنا.",
  "Monthly Salary Statistics":"إحصاءات الرواتب الشهرية",
  "Loan Request":"طلب القرض",
  'Status':'حالة',
  'Guarantor':"الضامن",
  'Request':'طلب',
  "Expense Request":"طلب النفقات",
  'Voucher':'قسيمة',
  'New Expense Request':'طلب نفقات جديد',
  'Submit':'يُقدِّم',
  'New Loan Request':"طلب قرض جديد",
  'Personal Loan':"القرض الشخصي",
  'Car Loan':"قرض السيارة",
  'Home Loan':"قرض المنزل",
  'Travel':'يسافر',
  'Office Supplies':"اللوازم المكتبية",
  'Meals':"الوجبات",
  'Leave':'يترك',
  'From Date':"من التاريخ",
  'To Date':"حتى الآن",
  'Sick Leave':"إجازة مرضية",
  'Casual Leave':"إجازة عارضة",
  'Paid Leave':"إجازة مدفوعة الأجر",
  'Work from Home':"العمل من المنزل",
  'Half Day':'نصف يوم',
  'Leave Request':'طلب الإجازة',
  'Pay Slip':"قسيمة الدفع",
  'Month':'شهر',
  'Attendance Request':"طلب الحضور",
  "New":"جديد",
  'Date & Time':'التاريخ والوقت',
  'Promotion Requests':'طلبات الترويج',
  "Manager":"مدير",
  "Chief":"رئيس",
  "Supervisor":"مشرف",
  "Delete":"يمسح",
  'Print':'مطبعة',
  'Log':'سجل',
  "Draft":"مسودة",
  'Doc No:':'رقم المستند:',
  "Doc Date:":"تاريخ المستند:",
  'Document Actions':"إجراءات المستند",
  'References':'مراجع',
  'Attachments':"المرفقات",
  'Drafts':"المسودات",
  'Document List':"قائمة المستندات",
  'Notes':'ملحوظات',
  'Search for an item...':'البحث عن عنصر',
  'Help & Support':"المساعدة والدعم",
  'Notifications':'إشعارات',
  'Settings':'إعدادات',
  "System":"نظام",
  "Master Setup":"الإعداد الرئيسي",
  "Employee Self Service":"خدمة الموظفين الذاتية",
  "Employee Management":"إدارة الموظفين",
  "View Profile":"عرض الملف الشخصي",
  "Change Password":"تغيير كلمة المرور",
  "Logout":"تسجيل الخروج",
  'DEPARTMENT WISE':'حسب القسم',
  'NATIONALITY WISE':'حسب الجنسية',
  'Announcement':'إعلان',
  'Type your annoucement here...':'اكتب إعلانك هنا...',
  'SEND':'يرسل',
  'SALARY':'مرتب',
  'LOCATION WISE':'من حيث الموقع',
  'HR COMPONENT WISE SALARY':"الراتب حسب مكونات الموارد البشرية",
  'SALARY BY COMPONENT':"الراتب حسب المكون",
  'FULL TIME':"دوام كامل",
  'FEMALE':"أنثى",
  'MALE':"MALE",
  'HEAD COUNT':"عدد الرؤوس",
  'REGISTRATION':"تسجيل",
  'TERMINATION':"الإنهاء",
  'HIRE':"يؤجر",
  'PART TIME':"دوام جزئى",
  'Payrole Period':'فترة الرواتب',
  'All DED Code':'جميع رموز DED',
  'Input Type':'نوع الإدخال',
  'Employee Name':'اسم الموظف',
  'Emp Code':'رمز الإمب',
  'Import Excel':'استيراد إكسل',
  'Export Excel':'تصدير إكسل',
  'Load Data':'تحميل البيانات',
  'Details':'تفاصيل',
  'Basic Salary':'الراتب الأساسي',
  'All Ded Code':'جميع رموز DED',
  'Select':'يختار',
  'payroll period':'فترة الرواتب',
  'Process Date':'تاريخ العملية',
  'Refresh':'ينعش',
  'Fill Reference':'تعبئة المرجع',
  'RefCode':'رمز المرجع',
  'Idle':'عاطل',
  'Total Minutes':'مجموع الدقائق',
  'Total Hours':'مجموع الساعات',
  'Out Time':'وقت الخروج',
  'In Time':'في الوقت المناسب',
  'Dept Code':'رمز القسم',
  'EmpCompID':'معرف الموظف',
  'Leave Type':'نوع الإجازة',
  'Ref No':'رقم المرجع',
  'Attendance from Date':'الحضور من تاريخ',
  'NP Balance':'رصيد NP',
  'Entitled':'مستحق',
  'No Days':'لا يوجد أيام',
  'CPR':'الإنعاش القلبي الرئوي',
  'Employee':'موظف',
  'Accomodation Name':'اسم مكان الإقامة',
  'Accomodation code':'كود الإقامة',
  'Road No':'الطريق رقم',
  'Building No':'رقم المبنى',
  'Area':'منطقة',
  'Flat No':'شقة رقم',
  'Block No':'رقم الكتلة',
  'Cost':'يكلف',
  'Airsec Name':'اسم ايرسيك',
  'Airsec code':'كود ايرسيك',
  'Default Airline':'شركة الطيران الافتراضية',
  'Type Something':'اكتب شيئا ما',
  'Al Arab':'أل عرب',
  'Company':'شركة',
  'Department Name':'اسم القسم',
  'Department code':'رمز القسم',
  'Department Type':'نوع القسم',
  'Department Head Name':'اسم رئيس القسم',
  'Dept head code':'رمز رئيس القسم',
  'Top Level':'المستوى الأعلى',
  'Sub Level':'المستوى الفرعي',
  'Sublevel':'المستوى الفرعي',
  'Action':'فعل',
  'Time':'وقت',
  '':'',
  '':'',
  '':'',
  '':'',
  '':'',
  
   // Add more translations as needed
 };
 
 export const getLanguageByEnglish = (english: string): string => {
   const { isRtl } = useDirection();
 
   if (isRtl) {
     return englishToArabic[english] || english; // Return Arabic if available, else fallback to English
   }
 
   return english; // Return English by default
 };
 